description: Test template description
name: test_template
settings:
  erosion:
    capacity: 4.0
    deposition: 0.1
    droplets: 1000
    erosion: 0.3
    evaporation: 0.02
    inertia: 0.05
    min_slope: 0.01
  height: 128
  height_power: 1.2
  lacunarity: 2.0
  land_scale: 0.3
  octaves: 6
  persistence: 0.5
  scale: 50.0
  water_level: 0.4
  width: 128
